name: Nightly Refresh

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run build
        run: poetry run ccx build
        
      - name: Download Commander Spellbook data (conditional)
        run: |
          # Download only if newer (using curl -z for conditional download)
          mkdir -p /tmp/spellbook_cache
          CACHE_FILE="/tmp/spellbook_cache/variants.json"
          if [ -f "$CACHE_FILE" ]; then
            curl -z "$CACHE_FILE" -o "$CACHE_FILE" -L https://json.commanderspellbook.com/variants.json
          else
            curl -o "$CACHE_FILE" -L https://json.commanderspellbook.com/variants.json
          fi

      - name: Run Commander Spellbook build
        run: |
          # Build spellbook artifacts
          poetry run ccx build-spellbook

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/*.csv.gz data/manifest.json data/spellbook/jsonl/*.jsonl.gz data/spellbook/csv/*.csv.gz data/spellbook/markdown/*.md.gz data/spellbook/*.jsonl.gz 2>/dev/null || true
          git diff --staged --quiet || git commit -m "Nightly refresh: Update Scryfall and Spellbook data"
          git push
